# Generated by Django 4.2 on 2023-04-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_auto_20230405_1551"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
    ]
