# Generated by Django 4.2 on 2023-04-17 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_remove_product_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["title", "-last_update"]},
        ),
    ]
